language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio run

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
